/**
 * PURPOSE:
 * Reusable pagination component that renders page number controls with truncated ellipsis (...),
 * previous/next navigation buttons, and responsive design token styling.
 *
 * CONTEXT/PARENT FILE:
 * Located in app/components/ for application-wide reusability.
 * Used by app/community/components/MembersDirectory.tsx.
 *
 * INPUTS / PARAMETERS:
 * - currentPage (number, Required): The currently active 1-indexed page.
 * - totalPages (number, Required): Total number of available pages.
 * - onPageChange (function, Required): Callback invoked when user selects a page.
 * - disabled (boolean, Optional): Whether pagination buttons should be disabled during loading.
 */

"use client";

import React, { useMemo, memo } from "react";
import { motion } from "framer-motion";
import { designTokens } from "@/app/constants/design-tokens";

interface PaginationProps {
  currentPage: number;
  totalPages: number;
  onPageChange: (page: number) => void;
  disabled?: boolean;
}

/**
 * getPaginationItems
 *
 * BEHAVIORAL MECHANISM:
 * Generates an array of page numbers and ellipsis ("...") placeholders based on strict rules:
 * Always includes Page 1 (Start), Page totalPages (End), currentPage - 1, currentPage, and currentPage + 1.
 * Any gaps greater than 1 between consecutive sorted page numbers are replaced with the string "...".
 *
 * PARAMETERS:
 * - currentPage (number): Active page number.
 * - totalPages (number): Maximum total pages.
 *
 * RETURNS:
 * - Array<number | "...">: Ordered list of page numbers and ellipsis tokens.
 */
export function getPaginationItems(
  currentPage: number,
  totalPages: number,
): (number | "...")[] {
  if (totalPages <= 1) return [1];

  const pagesSet = new Set<number>();

  // Always include start and end pages
  pagesSet.add(1);
  pagesSet.add(totalPages);
  console.log("This is total page", totalPages)
  // Include current page and adjacent neighbours
  if (currentPage - 1 >= 1) pagesSet.add(currentPage - 1);
  pagesSet.add(currentPage);
  if (currentPage + 1 <= totalPages) pagesSet.add(currentPage + 1);

  const sortedPages = Array.from(pagesSet).sort((a, b) => a - b);
  const result: (number | "...")[] = [];

  for (let i = 0; i < sortedPages.length; i++) {
    if (i > 0 && sortedPages[i] - sortedPages[i - 1] > 1) {
      result.push("...");
    }
    result.push(sortedPages[i]);
  }

  return result;
}

/**
 * Pagination
 *
 * BEHAVIORAL MECHANISM:
 * Renders previous/next navigation buttons and a row of page numbers generated by getPaginationItems.
 * Clicking a number or arrow triggers onPageChange. Active page gets highlighted primary styling.
 *
 * PARAMETERS:
 * - props (PaginationProps): Pagination controls state and callbacks.
 *
 * RETURNS:
 * - JSX.Element | null: The rendered pagination component, or null if totalPages <= 1.
 */
const Pagination = memo(function Pagination({
  currentPage,
  totalPages,
  onPageChange,
  disabled = false,
}: PaginationProps) {
  const paginationItems = useMemo(
    () => getPaginationItems(currentPage, totalPages),
    [currentPage, totalPages]
  );

  if (totalPages <= 1) return null;

  return (
    <div className="flex items-center justify-center gap-1.5 pt-3 select-none">
      {/* Previous Page Button */}
      <motion.button
        whileHover={{ scale: disabled || currentPage <= 1 ? 1 : 1.05 }}
        whileTap={{ scale: disabled || currentPage <= 1 ? 1 : 0.95 }}
        type="button"
        disabled={disabled || currentPage <= 1}
        onClick={() => onPageChange(currentPage - 1)}
        className={`w-8 h-8 rounded-lg border text-xs font-semibold flex items-center justify-center transition ${currentPage <= 1 || disabled
            ? "border-neutral-200 text-neutral-300 cursor-not-allowed bg-neutral-50"
            : `${designTokens.colors.border.default} text-neutral-600 hover:bg-neutral-100 cursor-pointer`
          }`}
        title="Previous Page"
      >
        ‹
      </motion.button>

      {/* Page Numbers */}
      {paginationItems.map((item, idx) => {
        if (item === "...") {
          return (
            <span
              key={`ellipsis-${idx}`}
              className="w-8 h-8 flex items-center justify-center text-xs text-neutral-400 font-semibold"
            >
              ...
            </span>
          );
        }

        const isCurrent = item === currentPage;

        return (
          <motion.button
            key={`page-${item}`}
            whileHover={{ scale: disabled || isCurrent ? 1 : 1.05 }}
            whileTap={{ scale: disabled || isCurrent ? 1 : 0.95 }}
            type="button"
            disabled={disabled}
            onClick={() => onPageChange(item)}
            className={`w-8 h-8 rounded-lg text-xs font-bold flex items-center justify-center transition cursor-pointer ${isCurrent
                ? `${designTokens.colors.bg.buttonPrimary} ${designTokens.colors.text.buttonPrimary} shadow-xs`
                : `border ${designTokens.colors.border.default} bg-white text-neutral-700 hover:bg-neutral-100`
              }`}
          >
            {item}
          </motion.button>
        );
      })}

      {/* Next Page Button */}
      <motion.button
        whileHover={{ scale: disabled || currentPage >= totalPages ? 1 : 1.05 }}
        whileTap={{ scale: disabled || currentPage >= totalPages ? 1 : 0.95 }}
        type="button"
        disabled={disabled || currentPage >= totalPages}
        onClick={() => onPageChange(currentPage + 1)}
        className={`w-8 h-8 rounded-lg border text-xs font-semibold flex items-center justify-center transition ${currentPage >= totalPages || disabled
            ? "border-neutral-200 text-neutral-300 cursor-not-allowed bg-neutral-50"
            : `${designTokens.colors.border.default} text-neutral-600 hover:bg-neutral-100 cursor-pointer`
          }`}
        title="Next Page"
      >
        ›
      </motion.button>
    </div>
  );
});

export default Pagination;
